version: "3"

services:
  db:
    image: postgres:13.3
    volumes:
      - ${DB_DATA_PATH}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
  redis:
    image: redis
    ports:
      - ${REDIS_PORT}:6379
